# Generated by Django 4.0 on 2025-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kana',
            options={'ordering': ['kana_type', 'romaji'], 'verbose_name': 'Kana Character', 'verbose_name_plural': 'Kana Characters'},
        ),
        migrations.AlterField(
            model_name='kana',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio pronunciation file.', null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='kana',
            name='character',
            field=models.CharField(help_text='The Japanese character.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='kana',
            name='kana_type',
            field=models.CharField(choices=[('Hiragana', 'Hiragana'), ('Katakana', 'Katakana'), ('Kanji', 'Kanji')], help_text='The type of the character.', max_length=20),
        ),
        migrations.AlterField(
            model_name='kana',
            name='romaji',
            field=models.CharField(help_text='The Romanization of the character.', max_length=20),
        ),
        migrations.DeleteModel(
            name='QuizScore',
        ),
    ]
