# Generated by Django 4.0 on 2025-08-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('learning', '0002_alter_kana_options_alter_kana_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('Hiragana', 'Hiragana'), ('Katakana', 'Katakana'), ('Kanji', 'Kanji')], max_length=20)),
                ('score', models.IntegerField(help_text='The score for the quiz (e.g., number of correct answers).')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
