# Generated by Django 4.0 on 2025-08-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_quizscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=1)),
                ('meaning', models.TextField()),
                ('onyomi', models.CharField(max_length=50)),
                ('kunyomi', models.CharField(max_length=50)),
                ('onyomi_example', models.CharField(max_length=100)),
                ('onyomi_example_reading', models.CharField(max_length=100)),
                ('kunyomi_example', models.CharField(max_length=100)),
                ('kunyomi_example_reading', models.CharField(max_length=100)),
                ('stroke_order_svg', models.TextField()),
            ],
        ),
    ]
